//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTest.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic-Tac-Toe is a game with minimum board 3x3..
        /// </summary>
        internal static string ErrMsg_BoardMinimumSize {
            get {
                return ResourceManager.GetString("ErrMsg_BoardMinimumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input sequence should not be empty..
        /// </summary>
        internal static string ErrMsg_SequenceShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ErrMsg_SequenceShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic Tac Toe board should be a square..
        /// </summary>
        internal static string ErrMsg_TicTacToeBoardShouldBeSquare {
            get {
                return ResourceManager.GetString("ErrMsg_TicTacToeBoardShouldBeSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner row length should be at least 3..
        /// </summary>
        internal static string ErrMsg_WinnerRowLengthMinimum {
            get {
                return ResourceManager.GetString("ErrMsg_WinnerRowLengthMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner row length should be less than board size..
        /// </summary>
        internal static string ErrMsg_WinnerRowLengthShouldBeLessThanBoardSize {
            get {
                return ResourceManager.GetString("ErrMsg_WinnerRowLengthShouldBeLessThanBoardSize", resourceCulture);
            }
        }
    }
}
